import { useRef,useState } from 'react';
import { ArrowUpRight,Check, ChevronDown,Download,ImagePlus,Layers,Maximize,Minus,Monitor,MousePointer2,Plus,RotateCcw,Smartphone,Sparkles,Upload,X,SlidersHorizontal } from 'lucide-react';
import { Section,Slider,Toggle,ResetButton } from './Controls';
import { Viewport } from './Viewport';
import type { ViewportHandle } from './Viewport';
import { initial,palettes,poses } from './types';
import type {Settings} from './types';
import { loadImage } from './scene';
export default function App(){const [s,setS]=useState<Settings>(initial),[screenshot,setScreenshot]=useState(''),[fileName,setFileName]=useState('探索山野 · 示例截图'),[imageInfo,setImageInfo]=useState('1206 × 2622'),[toast,setToast]=useState(''),[exporting,setExporting]=useState(false),[quality,setQuality]=useState(1),[selectedPose,setSelectedPose]=useState(0),[sideOpen,setSideOpen]=useState(true);const screenInput=useRef<HTMLInputElement>(null),bgInput=useRef<HTMLInputElement>(null),viewport=useRef<ViewportHandle>(null),toastTimer=useRef<ReturnType<typeof setTimeout>>(undefined);const update=<K extends keyof Settings>(key:K,value:Settings[K])=>setS(v=>({...v,[key]:value}));const notify=(message:string)=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000);};
 async function upload(file:File,target:'screen'|'bg'){if(!['image/png','image/jpeg','image/webp'].includes(file.type)){notify('请选择 PNG、JPG 或 WebP 图片。');return;}if(file.size>25*1024*1024){notify('图片不能超过 25 MB。');return;}const url=URL.createObjectURL(file);try{const img=await loadImage(url);if(img.width*img.height>64_000_000){URL.revokeObjectURL(url);notify('图片像素过大，请缩小到 6400 万像素以内。');return;}if(target==='screen'){if(screenshot)URL.revokeObjectURL(screenshot);setScreenshot(url);setFileName(file.name);setImageInfo(`${img.width} × ${img.height}`);}else{if(s.bgImage)URL.revokeObjectURL(s.bgImage);setS(v=>({...v,bgImage:url,bgType:'image'}));}notify(target==='screen'?'屏幕截图已更新':'背景图片已更新');}catch(e){URL.revokeObjectURL(url);notify((e as Error).message);}}
 async function exportImage(){setExporting(true);try{await viewport.current?.exportPNG(quality);notify('PNG 已导出，可以分享你的作品了。');}catch(e){notify((e as Error).message);}finally{setExporting(false);}}
 const dims=s.ratio.split(':').map(Number);const exportW=Math.round(1600*quality*Math.min(1,dims[0]/dims[1])),exportH=Math.round(exportW*dims[1]/dims[0]);
 return <div className="app"><header className="app-header"><a href="/" className="brand" aria-label="Frame Studio 首页"><span className="brand-symbol"><Layers size={22}/></span><span>frame<span className="brand-light">studio</span><span className="brand-dot">.</span></span></a><div className="project-name"><span className="header-divider"/>未命名作品<span className="local-label">本地创作</span></div><div className="header-actions"><span className="private-note"><span/>图片仅在本地处理</span><select className="quality-select" aria-label="导出倍率" value={quality} onChange={e=>setQuality(Number(e.target.value))}><option value={1}>1× PNG</option><option value={2}>2× PNG</option><option value={3}>3× PNG</option></select><button className="export-button" onClick={exportImage} disabled={exporting}><Download size={15}/>{exporting?'正在导出…':'导出图片'}<ArrowUpRight size={14}/></button></div></header>
 <div className="editor"><aside className={`inspector ${sideOpen?'':'collapsed'}`}><div className="inspector-heading"><span>制作你的下一张佳作</span><span className="small-dot"/></div>
 <Section title="屏幕截图"><button className="upload-zone" onClick={()=>screenInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])upload(e.dataTransfer.files[0],'screen');}}><span className="upload-icon"><ImagePlus size={21}/></span><strong>上传你的设计</strong><span>点击上传，或将截图拖到这里</span><small>PNG、JPG、WebP · 最大 25 MB</small></button><div className="asset-row"><div className="asset-thumbnail">{screenshot?<img src={screenshot} alt="已上传截图缩略图"/>:<img src="/alpine.jpg" alt="山野示例缩略图"/>}</div><div><strong title={fileName}>{fileName}</strong><span>{imageInfo}</span></div><button className="icon-button" title="替换截图" aria-label="替换截图" onClick={()=>screenInput.current?.click()}><Upload size={14}/></button></div><div className="inline-setting"><span>截图适配</span><select aria-label="截图适配" value={s.fit} onChange={e=>update('fit',e.target.value as Settings['fit'])}><option value="cover">填满屏幕</option><option value="contain">完整显示</option></select></div></Section>
 <Section title="渲染风格"><div className="style-options"><button className={s.style==='photo'?'style-choice selected':'style-choice'} aria-pressed={s.style==='photo'} onClick={()=>update('style','photo')}><span className="style-preview photo"><i/></span><span><Sparkles size={13}/>真实摄影感</span>{s.style==='photo'&&<Check className="style-check" size={12}/>}</button><button className={s.style==='minimal'?'style-choice selected':'style-choice'} aria-pressed={s.style==='minimal'} onClick={()=>update('style','minimal')}><span className="style-preview minimal"><i/></span><span><Layers size={13}/>2.5D 简约</span>{s.style==='minimal'&&<Check className="style-check" size={12}/>}</button></div></Section>
 <Section title="角度与构图" action={<ResetButton onClick={()=>{setS(v=>({...v,rx:initial.rx,ry:initial.ry,rz:initial.rz,perspective:35,scale:90}));setSelectedPose(0);}}/>}><div className="pose-grid">{poses.map((p,i)=><button key={p.name} className={`pose-choice ${selectedPose===i?'active':''}`} aria-label={p.name} title={p.name} aria-pressed={selectedPose===i} onClick={()=>{setS(v=>({...v,rx:p.rx,ry:p.ry,rz:p.rz}));setSelectedPose(i);}}><Smartphone size={23} style={{transform:`perspective(80px) rotateX(${p.rx}deg) rotateY(${p.ry}deg) rotateZ(${-p.rz}deg)`}}/><span>{p.name.slice(0,2)}</span></button>)}</div><Slider label="水平旋转" value={s.ry} min={-180} max={180} onChange={v=>{update('ry',v);setSelectedPose(-1);}}/><Slider label="俯仰角度" value={s.rx} min={-180} max={180} onChange={v=>{update('rx',v);setSelectedPose(-1);}}/><Slider label="画面倾斜" value={s.rz} min={-180} max={180} onChange={v=>{update('rz',v);setSelectedPose(-1);}}/><Slider label={s.style==='minimal'?'透视（正交视图）':'相机透视'} value={s.perspective} min={10} max={75} onChange={v=>update('perspective',v)} disabled={s.style==='minimal'}/><Slider label="模型大小" value={s.scale} min={35} max={150} unit="%" onChange={v=>update('scale',v)}/></Section>
 <Section title="背景"><div className="segmented">{([['gradient','渐变'],['solid','纯色'],['image','图片']] as const).map(([key,label])=><button key={key} className={s.bgType===key?'active':''} aria-pressed={s.bgType===key} onClick={()=>update('bgType',key)}>{label}</button>)}</div>{s.bgType==='image'?<><button className="background-upload" onClick={()=>bgInput.current?.click()}>{s.bgImage?<img src={s.bgImage} alt="自定义背景"/>:<ImagePlus size={22}/>}<span>{s.bgImage?'更换背景图片':'上传背景图片'}</span></button>{s.bgImage&&<button className="text-button" onClick={()=>{URL.revokeObjectURL(s.bgImage);setS(v=>({...v,bgImage:'',bgType:'gradient'}));}}>移除图片</button>}</>:<><div className="swatches">{palettes.map(([a,b],i)=><button key={a} title={['青苔','砂岩','暮紫','陶土','雾蓝','深林'][i]} aria-label={`${['青苔','砂岩','暮紫','陶土','雾蓝','深林'][i]}配色`} className={s.color1===a?'chosen':''} style={{background:s.bgType==='solid'?a:`linear-gradient(135deg,${a},${b})`}} onClick={()=>setS(v=>({...v,color1:a,color2:b}))}>{s.color1===a&&<Check size={14}/>}</button>)}</div><div className="color-fields"><label><input type="color" aria-label="背景颜色一" value={s.color1} onChange={e=>update('color1',e.target.value)}/><span>{s.color1.toUpperCase()}</span></label>{s.bgType==='gradient'&&<label><input type="color" aria-label="背景颜色二" value={s.color2} onChange={e=>update('color2',e.target.value)}/><span>{s.color2.toUpperCase()}</span></label>}</div>{s.bgType==='gradient'&&<Slider label="渐变方向" value={s.gradientAngle} min={0} max={360} onChange={v=>update('gradientAngle',v)}/>}</>}</Section>
 <Section title="材质与光影"><div className="inline-setting"><span>机身颜色</span><div className="frame-colors">{[['#c9cebc','鼠尾草'],['#dad6e6','薰衣草'],['#b7d2e6','雾蓝'],['#e7e8e4','白色'],['#454946','黑色']].map(([c,name])=><button key={c} title={name} aria-label={`${name}机身`} aria-pressed={s.frame===c} className={s.frame===c?'chosen':''} style={{background:c}} onClick={()=>update('frame',c)}>{s.frame===c&&<Check size={11}/>}</button>)}</div></div><Slider label="悬浮阴影" value={s.shadow} min={0} max={100} unit="%" onChange={v=>update('shadow',v)}/><Slider label="玻璃反光" value={s.reflection} min={0} max={100} unit="%" onChange={v=>update('reflection',v)} disabled={s.style==='minimal'}/><Toggle label="显示灵动岛" value={s.island} onChange={()=>update('island',!s.island)}/></Section><div className="inspector-footer"><Monitor size={13}/>浏览器就是你的摄影棚。</div></aside>
 <main className="workspace"><div className="workspace-toolbar"><div className="canvas-label"><button className="icon-button sidebar-toggle" aria-label="显示或隐藏设置" onClick={()=>setSideOpen(!sideOpen)}><SlidersHorizontal size={16}/></button><span className="canvas-icon"><Smartphone size={15}/></span><span>iPhone 17</span><span className="device-meta">6.3 英寸</span></div><div className="toolbar-right"><label className="ratio-control"><Maximize size={13}/><select aria-label="画布比例" value={s.ratio} onChange={e=>update('ratio',e.target.value)}><option value="4:3">4 : 3</option><option value="1:1">1 : 1</option><option value="16:9">16 : 9</option><option value="3:4">3 : 4</option><option value="9:16">9 : 16</option></select><ChevronDown size={12}/></label><button className="icon-button" title="重置所有设置" aria-label="重置所有设置" onClick={()=>{setS({...initial});setSelectedPose(0);notify('已恢复默认构图与样式');}}><RotateCcw size={15}/></button></div></div>
 <div className="canvas-area"><div className="artboard-wrap" style={{'--ratio':dims[0]/dims[1]} as React.CSSProperties}><Viewport ref={viewport} settings={s} screenshot={screenshot} onRotate={(rx,ry)=>{setS(v=>({...v,rx:Math.round(rx),ry:Math.round(ry)}));setSelectedPose(-1);}} onZoom={delta=>setS(v=>({...v,scale:Math.max(35,Math.min(150,v.scale+delta))}))} onDrop={file=>upload(file,'screen')} onError={notify}/></div><div className="canvas-caption"><span>你的设计，值得更好的呈现。</span><span>{exportW} × {exportH} px</span></div></div>
 <div className="workspace-bottom"><div className="interaction-hint"><MousePointer2 size={13}/><span>拖动旋转</span><span className="dot-separator">·</span><span>滚轮缩放</span></div><div className="zoom-control"><button className="icon-button" aria-label="缩小模型" onClick={()=>update('scale',Math.max(35,s.scale-5))}><Minus size={14}/></button><button className="zoom-value" title="恢复默认缩放" onClick={()=>update('scale',90)}>{s.scale}%</button><button className="icon-button" aria-label="放大模型" onClick={()=>update('scale',Math.min(150,s.scale+5))}><Plus size={14}/></button></div><span className="render-status"><span/>{s.style==='photo'?'实时 3D 渲染':'2.5D 正交渲染'}</span></div></main></div>
 <footer className="app-footer"><span>为好设计，多一个好角度。</span><span><span className="status-dot"/>所有图片在本地处理，不上传服务器</span></footer><input ref={screenInput} className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" aria-label="上传屏幕截图" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0],'screen');e.target.value='';}}/><input ref={bgInput} className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" aria-label="上传背景图片" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0],'bg');e.target.value='';}}/>{toast&&<div className="toast" role="status"><Check size={16}/>{toast}<button className="icon-button" aria-label="关闭提示" onClick={()=>setToast('')}><X size={14}/></button></div>}</div>;
}
