import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import type { Settings } from './types';

function shape(w:number,h:number,r:number){const s=new THREE.Shape(), x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s;}
function panel(w:number,h:number,r:number,depth:number,material:THREE.Material){const geo=new THREE.ExtrudeGeometry(shape(w,h,r),{depth,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:3,steps:1,curveSegments:16});geo.translate(0,0,-depth/2);return new THREE.Mesh(geo,material);}
function face(w:number,h:number,r:number,material:THREE.Material){const g=new THREE.ShapeGeometry(shape(w,h,r),24);const pos=g.attributes.position,uv=g.attributes.uv;for(let i=0;i<pos.count;i++)uv.setXY(i,pos.getX(i)/w+.5,pos.getY(i)/h+.5);return new THREE.Mesh(g,material);}
export function loadImage(url:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('图片无法读取，请尝试 PNG、JPG 或 WebP 格式。'));im.src=url;});}
export function cover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,x:number,y:number,w:number,h:number,contain=false){const ratio=contain?Math.min(w/img.width,h/img.height):Math.max(w/img.width,h/img.height);ctx.drawImage(img,x+(w-img.width*ratio)/2,y+(h-img.height*ratio)/2,img.width*ratio,img.height*ratio);}
export async function demoScreen(){const c=document.createElement('canvas');c.width=1206;c.height=2622;const x=c.getContext('2d')!;x.fillStyle='#f6f3e9';x.fillRect(0,0,c.width,c.height);try{const im=await loadImage('/alpine.jpg');cover(x,im,0,0,1206,1720);}catch{const g=x.createLinearGradient(0,0,1206,1700);g.addColorStop(0,'#9faf94');g.addColorStop(1,'#354c3c');x.fillStyle=g;x.fillRect(0,0,1206,1720);}const shade=x.createLinearGradient(0,0,0,1700);shade.addColorStop(0,'#10271c44');shade.addColorStop(.5,'#17291c00');shade.addColorStop(1,'#15251fe8');x.fillStyle=shade;x.fillRect(0,0,1206,1720);x.fillStyle='#fffff5';x.font='600 40px system-ui';x.fillText('9:41',85,95);x.fillText('▰',1050,95);x.font='500 40px system-ui';x.fillText('elsewhere',86,250);x.font='34px system-ui';x.fillText('↗',1080,250);x.font='32px system-ui';x.fillText('LESS SCROLL. MORE SOUL.',86,1180);x.font='100px Georgia';x.fillText('Find your',80,1320);x.fillText('somewhere.',80,1440);x.font='34px system-ui';x.fillText('A little further from the everyday.',86,1540);x.fillStyle='#394b3e';x.font='28px system-ui';x.fillText('THE SLOW JOURNAL',86,1830);x.font='72px Georgia';x.fillText('Take the scenic route.',80,1950);x.fillStyle='#7a7b6d';x.font='34px system-ui';x.fillText('Places to pause. Stories to bring home.',86,2035);x.strokeStyle='#c8ccbc';x.lineWidth=2;x.beginPath();x.moveTo(86,2140);x.lineTo(1120,2140);x.stroke();x.fillStyle='#394b3e';x.font='38px system-ui';x.fillText('Explore the collection',86,2250);x.fillText('↗',1070,2250);x.font='28px system-ui';x.fillText('DISCOVER',95,2460);x.fillText('JOURNAL',504,2460);x.fillText('SAVED',950,2460);x.fillStyle='#26382b';x.beginPath();x.roundRect(425,2560,356,13,7);x.fill();return c;}
export class PhoneScene{
 renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera();ortho=new THREE.OrthographicCamera();phone=new THREE.Group();bodyMat=new THREE.MeshStandardMaterial({color:'#c9cebc',metalness:.85,roughness:.26});backMat=new THREE.MeshPhysicalMaterial({color:'#c9cebc',metalness:.15,roughness:.35,clearcoat:.6});screenMat=new THREE.MeshBasicMaterial({toneMapped:false});glassMat=new THREE.MeshBasicMaterial({transparent:true,opacity:.1,depthWrite:false});island:THREE.Mesh;screenCanvas=document.createElement('canvas');screenTexture:THREE.CanvasTexture;settings:Settings;image:HTMLImageElement|HTMLCanvasElement|null=null;env:THREE.WebGLRenderTarget;disposed=false;light:THREE.DirectionalLight;
 constructor(canvas:HTMLCanvasElement,settings:Settings){this.settings=settings;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0x000000,0);this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.3;const pm=new THREE.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.env=pm.fromScene(room,.04);this.scene.environment=this.env.texture;room.dispose();pm.dispose();this.scene.add(new THREE.HemisphereLight('#fff7ee','#566558',3));this.light=new THREE.DirectionalLight('#fffaf3',5);this.light.position.set(-5,7,8);this.scene.add(this.light);const rim=new THREE.DirectionalLight('#d8e7ff',3);rim.position.set(5,1,-3);this.scene.add(rim);this.scene.add(this.phone);
 const body=panel(3.2,6.696,.47,.306,this.bodyMat);this.phone.add(body);const back=face(3.12,6.62,.45,this.backMat);back.position.z=-.18;back.rotation.y=Math.PI;this.phone.add(back);const bezel=panel(3.15,6.65,.47,.03,new THREE.MeshStandardMaterial({color:'#101512',metalness:.5,roughness:.18}));bezel.position.z=.177;this.phone.add(bezel);
 this.screenCanvas.width=1206;this.screenCanvas.height=2622;this.screenTexture=new THREE.CanvasTexture(this.screenCanvas);this.screenTexture.colorSpace=THREE.SRGBColorSpace;this.screenTexture.anisotropy=this.renderer.capabilities.getMaxAnisotropy();this.screenMat.map=this.screenTexture;const screen=face(3.026,6.55,.405,this.screenMat);screen.position.z=.222;this.phone.add(screen);
 const glassCanvas=document.createElement('canvas');glassCanvas.width=256;glassCanvas.height=512;const gc=glassCanvas.getContext('2d')!,gr=gc.createLinearGradient(0,0,256,512);gr.addColorStop(0,'#ffffff66');gr.addColorStop(.43,'#ffffff00');gr.addColorStop(.48,'#ffffff0a');gr.addColorStop(1,'#ffffff00');gc.fillStyle=gr;gc.fillRect(0,0,256,512);this.glassMat.map=new THREE.CanvasTexture(glassCanvas);const glass=face(3.027,6.55,.405,this.glassMat);glass.position.z=.225;this.phone.add(glass);
 this.island=face(.88,.255,.127,new THREE.MeshBasicMaterial({color:'#080b0a'}));this.island.position.set(0,3.00,.238);this.phone.add(this.island);const lens=new THREE.Mesh(new THREE.CircleGeometry(.045,24),new THREE.MeshBasicMaterial({color:'#142329'}));lens.position.set(.29,0,.003);this.island.add(lens);
 for(const [x,y,h] of [[-1.627,1.66,.25],[-1.627,.93,.53],[-1.627,.23,.53],[1.627,.6,.84],[1.627,-1.24,.58]]){const b=panel(.045,h,.022,.16,this.bodyMat);b.position.set(x,y,0);this.phone.add(b);}
 const bump=panel(.91,1.72,.45,.11,this.backMat);bump.position.set(.89,2.24,-.245);this.phone.add(bump);for(const y of [2.66,1.86]){const ring=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.13,48),this.bodyMat);ring.rotation.x=Math.PI/2;ring.position.set(.89,y,-.35);this.phone.add(ring);const lens=new THREE.Mesh(new THREE.CircleGeometry(.279,48),new THREE.MeshPhysicalMaterial({color:'#121e24',metalness:.55,roughness:.08,clearcoat:1}));lens.rotation.y=Math.PI;lens.position.set(.89,y,-.422);this.phone.add(lens);const inner=new THREE.Mesh(new THREE.CircleGeometry(.125,32),new THREE.MeshBasicMaterial({color:'#1c2f40'}));inner.rotation.y=Math.PI;inner.position.set(.89,y,-.424);this.phone.add(inner);}const flash=new THREE.Mesh(new THREE.CircleGeometry(.1,24),new THREE.MeshBasicMaterial({color:'#fff6df'}));flash.rotation.y=Math.PI;flash.position.set(.23,2.3,-.2);this.phone.add(flash);
 this.update(settings);
 }
 setImage(im:HTMLImageElement|HTMLCanvasElement){this.image=im;this.updateTexture();}
 updateTexture(){if(!this.image)return;const ctx=this.screenCanvas.getContext('2d')!;ctx.fillStyle='#151816';ctx.fillRect(0,0,1206,2622);cover(ctx,this.image as HTMLImageElement,0,0,1206,2622,this.settings.fit==='contain');this.screenTexture.needsUpdate=true;this.render();}
 update(s:Settings){const fitChanged=this.settings.fit!==s.fit;this.settings=s;this.phone.rotation.set(THREE.MathUtils.degToRad(s.rx),THREE.MathUtils.degToRad(s.ry),THREE.MathUtils.degToRad(s.rz));this.phone.scale.setScalar(s.scale/100);this.bodyMat.color.set(s.frame);this.backMat.color.set(s.frame);const photo=s.style==='photo';this.bodyMat.metalness=photo?.85:.05;this.bodyMat.roughness=photo?.26:.85;this.backMat.metalness=photo?.15:0;this.scene.environmentIntensity=photo?1:.25;this.light.intensity=photo?5:2;this.glassMat.opacity=photo?s.reflection/100:0;this.island.visible=s.island;if(fitChanged)this.updateTexture();this.render();}
 render(){if(this.disposed)return;const canvas=this.renderer.domElement;const aspect=canvas.width/canvas.height;const viewHeight=aspect<1?10.1/aspect:10.1;this.camera.fov=this.settings.perspective;this.camera.aspect=aspect;this.camera.near=.1;this.camera.far=200;this.camera.position.set(0,0,viewHeight/(2*Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2))));this.camera.updateProjectionMatrix();this.ortho.left=-viewHeight*aspect/2;this.ortho.right=viewHeight*aspect/2;this.ortho.top=viewHeight/2;this.ortho.bottom=-viewHeight/2;this.ortho.near=.1;this.ortho.far=200;this.ortho.position.set(0,0,30);this.ortho.updateProjectionMatrix();this.renderer.render(this.scene,this.settings.style==='minimal'?this.ortho:this.camera);}
 resize(w:number,h:number){this.renderer.setSize(w,h,false);this.render();}
 dispose(){this.disposed=true;this.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});this.screenTexture.dispose();this.glassMat.map?.dispose();this.env.dispose();this.renderer.dispose();}
}
export function paintBackground(ctx:CanvasRenderingContext2D,w:number,h:number,s:Settings,img:HTMLImageElement|null){ctx.clearRect(0,0,w,h);if(s.bgType==='image'&&img){cover(ctx,img,0,0,w,h);}else if(s.bgType==='gradient'){const a=(s.gradientAngle-90)*Math.PI/180,dx=Math.cos(a)*w/2,dy=Math.sin(a)*h/2;const g=ctx.createLinearGradient(w/2-dx,h/2-dy,w/2+dx,h/2+dy);g.addColorStop(0,s.color1);g.addColorStop(1,s.color2);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}else{ctx.fillStyle=s.color1;ctx.fillRect(0,0,w,h);}if(s.shadow>0){ctx.save();ctx.translate(w*.52,h*.84);ctx.scale(w*.23,h*.055);const shadow=ctx.createRadialGradient(0,0,0,0,0,1);shadow.addColorStop(0,`rgba(18,30,20,${s.shadow/180})`);shadow.addColorStop(1,'rgba(18,30,20,0)');ctx.fillStyle=shadow;ctx.fillRect(-1,-1,2,2);ctx.restore();}}
